# Over rides for default values in Helm Charts
destination: &ci_cd_ns labs-ci-cd

##############
# 🛎 Jenkins Custom Values
#############
jenkins_values: &jenkins_values
  persistence: false
  source_secret:
    name: gitlab-auth
    username: idm-sa
    password: thisisdefinitelynotmypassword  

##############
# 🛎 Sonarqube Custom Values
#############

##############
# 🛎 Pact Broker Custom Values
#############
pact_broker_values: &pact_broker_values
  secrets:
    name: pact-broker-secrets
    keys:
      pactBrokerDatabaseUsername: pact_broker_database_username
      pactBrokerDatabasePassword: pact_broker_database_password
      pactBrokerAdmin: pact_broker_admin
      pactBrokerAdminPassword: pact_broker_admin_password
      pactBrokerBasicAuthUsername: pact_broker_user
      pactBrokerBasicAuthPassword: pact_broker_user_password
    values:
      pactBrokerDatabaseUsername: pact_broker_user
      pactBrokerDatabasePassword: thisisdefinitelynotmypassword
      pactBrokerAdmin: admin
      pactBrokerAdminPassword: thisisdefinitelynotmypassword
      pactBrokerBasicAuthUsername: dev
      pactBrokerBasicAuthPassword: thisisdefinitelynotmypassword

##############
# 🛎 Sonatype Nexus Custom Values
#############
nexus_values: &nexus_values
  nexus:
    imageTag: 3.19.1
    service:
      type: ClusterIP
    podAnnotations: {}
    securityContextEnabled: false

  route:
    enabled: true
    name: nexus
    portName: nexus-service
    path: null

  nexusProxy:
    enabled: false

  persistence:
    storageSize: 5Gi  

  serviceAccount:
    name: nexus
    annotations: {}

  deployment:
    annotations: {}
    initContainers:
      - name: k8s-plugin-puller
        image: curlimages/curl:latest
        imagePullPolicy: Always
        command: ['sh','-c']
        args: ['curl -o /k8s-plugin/nexus-openshift-plugin.jar https://github.com/sonatype-nexus-community/nexus-kubernetes-openshift-releases/download/v0.2.8/nexus-openshift-plugin-0.2.8.jar']
        volumeMounts:
          - name: k8s-plugin
            mountPath: /k8s-plugin
    additionalVolumes:
      - name: k8s-plugin
        emptyDir: {}
    additionalVolumeMounts:
      - mountPath: /opt/sonatype/nexus/deploy/nexus-openshift-plugin.jar
        name: k8s-plugin
        subPath: nexus-openshift-plugin.jar

  secret:
    enabled: false
    mountPath:
    readOnly:
    data:
  
  service:
    enabled: true 
    name: nexus-service
    labels: {}
    annotations: {}
    portName: nexus-service
    port: 8081
    targetPort: 8081
    ports: []

##############
# 🛎 Zalenium Custom Values
#############
## TODO: Update source URL as upstream when ArgoCD version is greater 1.5.0 or above
zalenium_values: &zalenium_values
  hub:
    serviceType: ClusterIP
    openshift:
      deploymentConfig:
        enabled: true
      route: 
        enabled: true
    persistence:
      enabled: false
    serviceAccount:
      create: false
    desiredContainers: 0
    podAnnotations:
      app: zalenium

##############
# 🐙 Argo Ignore Differences 
#############
ignore_differences: &ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:        
    - /spec/triggers
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress


##############
# 🛎 Argo App of Apps declaration
#############

# enabled true on an app is to tell helm to create an argo app cr for this item
applications:
  - name: nexus
    enabled: true
    source: https://github.com/Oteemo/charts.git
    source_path: charts/sonatype-nexus
    source_ref: "sonatype-nexus-1.26.2"
    sync_policy_automated: true
    destination: *ci_cd_ns 
    values:
      *nexus_values
    ignore_differences: *ignore_differences
  - name: jenkins
    enabled: true 
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-0.0.8"
    sync_policy_automated: true
    destination: *ci_cd_ns 
    values:
      *jenkins_values
    ignore_differences: *ignore_differences
  - name: pact-broker
    enabled: true 
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/pact-broker
    source_ref: "pact-broker-0.0.1"
    sync_policy_automated: true
    destination: *ci_cd_ns
    values:
      *pact_broker_values
  - name: sonarqube
    enabled: true 
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/sonarqube
    source_ref: "sonarqube-0.0.4"
    sync_policy_automated: true
    destination: *ci_cd_ns
  - name: crw
    enabled: true
    destination: crw
    source: https://github.com/eformat/argocd
    source_path: crw/base
    source_ref: master
    sync_policy_automated: true
    no_helm: true
  - name: zalenium
    enabled: true 
    source: https://github.com/ckavili/zalenium.git
    source_path: charts/zalenium
    source_ref: "master"
    sync_policy_automated: true
    destination: *ci_cd_ns
    values:
      *zalenium_values
    ignore_differences: *ignore_differences
